// Build a self-contained binary (Node SEA) for the current OS/arch (doc 05).
// CI runs this on macos-14 (arm64), macos-13 (x64), and windows-latest (x64)
// using the official Node from actions/setup-node (its node carries the SEA fuse).
//
// Local note: a Homebrew node will NOT work (its shared libnode lacks the SEA
// fuse). Point NODE_SEA_BASE at an official node binary to build locally.
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dist = path.join(root, "dist");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const version = pkg.version;
const FUSE = "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2";

const platform = process.platform;
const arch = process.arch;

function assetName() {
  if (platform === "win32") {
    return "codex-deepseek-bridge-win-x64.exe";
  }
  if (platform === "darwin") {
    return arch === "arm64" ? "codex-deepseek-bridge-macos" : "codex-deepseek-bridge-macos-x64";
  }
  return `codex-deepseek-bridge-${platform}-${arch}`;
}

function run(cmd, cmdArgs, options = {}) {
  execFileSync(cmd, cmdArgs, { stdio: "inherit", ...options });
}

async function main() {
  fs.rmSync(dist, { recursive: true, force: true });
  fs.mkdirSync(dist, { recursive: true });

  const bundlePath = path.join(dist, "bundle.cjs");
  const blobPath = path.join(dist, "sea-prep.blob");
  const seaConfigPath = path.join(dist, "sea-config.json");
  const outPath = path.join(dist, assetName());

  // The blob is node-version-specific, so it must be generated by the SAME node
  // that becomes the base binary (official, statically-linked node).
  const seaBase = process.env.NODE_SEA_BASE || process.execPath;

  // 1. Bundle ESM -> CJS and inject the version constant for the binary.
  await esbuild.build({
    entryPoints: [path.join(root, "bin", "codex-deepseek-bridge.mjs")],
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node18",
    banner: { js: `globalThis.__DSCB_VERSION__=${JSON.stringify(version)};` },
    logOverride: { "empty-import-meta": "silent" },
    outfile: bundlePath,
  });

  // 2. Generate the SEA blob with the base node.
  fs.writeFileSync(
    seaConfigPath,
    `${JSON.stringify({ main: bundlePath, output: blobPath, disableExperimentalSEAWarning: true }, null, 2)}\n`,
  );
  run(seaBase, ["--experimental-sea-config", seaConfigPath]);

  // 3. Copy the base node binary.
  fs.copyFileSync(seaBase, outPath);
  fs.chmodSync(outPath, 0o755);

  // 4. Inject the blob (codesign dance on macOS).
  if (platform === "darwin") {
    run("codesign", ["--remove-signature", outPath]);
  }
  const postjectCli = require.resolve("postject/dist/cli.js");
  const postjectArgs = [postjectCli, outPath, "NODE_SEA_BLOB", blobPath, "--sentinel-fuse", FUSE];
  if (platform === "darwin") {
    postjectArgs.push("--macho-segment-name", "NODE_SEA");
  }
  run(process.execPath, postjectArgs);
  if (platform === "darwin") {
    run("codesign", ["--sign", "-", outPath]);
  }

  // 5. Publish a checksum next to the artifact.
  const bytes = fs.readFileSync(outPath);
  const digest = crypto.createHash("sha256").update(bytes).digest("hex");
  fs.writeFileSync(`${outPath}.sha256`, `${digest}  ${assetName()}\n`);

  // 6. Minimal smoke: the binary reports its own version.
  const printed = execFileSync(outPath, ["version"], {
    encoding: "utf8",
    env: { ...process.env, DSCB_UPDATE_CHECK: "off" },
  });
  if (!printed.includes(version)) {
    throw new Error(`binary smoke test failed: version not reported (${printed.trim()})`);
  }

  process.stdout.write(`Built ${outPath}\nsha256 ${digest}\n${printed}`);
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.stack || error.message : String(error)}\n`);
  process.exitCode = 1;
});
